name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test_vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vitest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn && yarn prisma generate

      - name: Run tests
        run: yarn run test

  integration_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IntegrationTests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run integration script
        run: npm run test:integration
