name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test_vitest:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.files.*.path, 'vitest/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: vitest
        run: yarn && yarn prisma generate

      - name: Run tests
        working-directory: vitest
        run: yarn run test

  integration_test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.files.*.path, 'IntegrationTests/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp ./IntegrationTests/.env.example ./IntegrationTests/.env

      - name: Run integration script
        run: cd IntegrationTests && yarn run test:integration
